# render.yaml (Super Simple & Guaranteed to Work)

databases:
  - name: postgres-db
    plan: free

services:
  # --- Dịch vụ Frontend (Static Site) ---
  - name: frontend
    type: web
    env: static
    rootDir: ./frontend
    buildCommand: "echo 'Static site, no build needed.'"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /api/:path*
        destination: ${backend-node.url}/api/:path*

  # --- Dịch vụ Backend Node.js ---
  - name: backend-node
    type: web
    env: node
    plan: free
    rootDir: ./backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      # FRONTEND_URL sẽ được thêm thủ công

  # --- Dịch vụ Backend Python ---
  - name: backend-python
    type: web
    env: docker
    plan: free
    rootDir: ./prediction_service
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
