# render.yaml (Final Version - Corrected)

databases:
  - name: postgres-db
    plan: free

services:
  # --- Dịch vụ Frontend (Static Site) ---
  - name: frontend
    type: web
    env: static
    rootDir: ./frontend
    buildCommand: "echo 'Static site, no build needed.'"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /api/:path*
        destination: ${backend-node.url}/api/:path*

  # --- Dịch vụ Backend Node.js ---
  - name: backend-node
    type: web
    env: node
    plan: free
    rootDir: ./backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      # BIẾN FRONTEND_URL SẼ ĐƯỢC THÊM THỦ CÔNG SAU

  # --- Dịch vụ Backend Python ---
  - name: backend-python
    type: web
    env: docker
    plan: free
    rootDir: ./prediction_service
    dockerfilePath: ./Dockerfile
    healthCheckPath: /

  # --- Job khởi tạo Database ---
  - name: db-init-job
    type: worker # Job là loại đúng cho tác vụ chạy một lần
    # Chúng ta cần chỉ định một môi trường có psql
    # Môi trường 'image' với postgres là một lựa chọn
    image:
      url: postgres:16-alpine # Sử dụng một image postgres nhẹ có psql
    rootDir: ./backend
    startCommand: "psql $$DATABASE_URL -f init.sql"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
