databases:
  - name: postgres-db
    plan: free

services:
  # --- Frontend ---
  - name: frontend
    type: web
    env: static
    rootDir: ./frontend
    buildCommand: "echo 'Static site, no build needed.'"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /api/:path*
        destination: ${backend-node.url}/api/:path*

  # --- Backend Node.js ---
  - name: backend-node
    type: web
    env: node
    plan: free
    rootDir: ./backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: DATABASE_URL # Cung cấp đúng biến này
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PYTHON_SERVICE_URL
        fromService:
          type: web
          name: backend-python
          property: hostport

  # --- Dịch vụ Backend Python ---
  - name: backend-python
    type: web
    env: docker
    plan: free
    rootDir: ./prediction_service
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
