# render.yaml (Corrected Syntax and Logic)

databases:
  - name: postgres-db # Sử dụng một tên nhất quán và rõ ràng
    plan: free
    # databaseName và user có thể bỏ qua, Render sẽ tự tạo và inject

services:
  # --- Dịch vụ Frontend (Static Site) ---
  - name: frontend
    type: web
    env: static
    rootDir: ./frontend
    buildCommand: "echo 'Static site, no build needed.'"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /api/:path*
        destination: ${backend-node.url}/api/:path*

  # --- Dịch vụ Backend Node.js ---
  - name: backend-node
    type: web
    env: node
    plan: free
    rootDir: ./backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db # Tên phải khớp với khối 'databases'
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      # Thêm FRONTEND_URL để xử lý CORS
      - key: FRONTEND_URL
        fromService:
          type: web
          name: frontend
          property: url

  # --- Dịch vụ Backend Python ---
  - name: backend-python
    type: web
    env: docker
    plan: free
    rootDir: ./prediction_service
    dockerfilePath: ./Dockerfile
    healthCheckPath: /

  # --- Job khởi tạo Database ---
  - name: db-init-job
    type: worker # Phải ngang hàng với các services khác
    rootDir: ./backend
    startCommand: "psql $DATABASE_URL -f init.sql"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db # Tên phải khớp với khối 'databases'
          property: connectionString
