# render.yaml (Final Final Version)

services:
  # --- Dịch vụ Frontend (Static Site) ---
  - name: frontend
    type: web
    env: static
    rootDir: ./frontend
    buildCommand: npm run build  # or whatever your static site build command is
    staticPublishPath: dist      # change to your actual build output folder (e.g., build, dist)
    routes:
      - type: rewrite
        source: /api/:path*
        destination: ${backend-node.url}/api/:path*

  # --- Dịch vụ Backend Node.js ---
  - name: backend-node
    type: web
    env: node
    plan: free
    rootDir: ./backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: mysql-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: mysql-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mysql-db
          property: password
      - key: DB_DATABASE
        fromDatabase:
          name: mysql-db
          property: database
      - key: JWT_SECRET
        generateValue: true

  # --- Dịch vụ Backend Python ---
  - name: backend-python
    type: web
    env: docker
    plan: free
    rootDir: ./prediction_service
    dockerfilePath: ./Dockerfile
    healthCheckPath: /

databases:
  - name: mysql-db
    databaseName: navigation_app_db
    user: db_user
    plan: free
