# render.yaml (Final Version for your exact file structure)
databases:
  - name: mysql-db
    databaseName: navigation_app_db
    user: db_user
    plan: free
    
services:
  # --- Dịch vụ Frontend (Static Site) ---
  - name: frontend
    type: web
    env: static
    # rootDir trỏ đến thư mục chứa các file HTML, CSS của bạn
    rootDir: ./frontend 
    # Vì không có bước build, chúng ta chỉ cần một lệnh vô hại
    buildCommand: "echo 'Static site, no build step needed.'"
    # Render sẽ phục vụ các file trực tiếp từ thư mục `rootDir`
    staticPublishPath: . 
    routes:
      - type: rewrite
        source: /api/:path*
        destination: ${backend-node.url}/api/:path*

 # --- Dịch vụ Backend Node.js ---
  - name: backend-node
    type: web
    env: node
    plan: free
    rootDir: ./backend
    buildCommand: npm install
    startCommand: node server.js
 envVars:
      # Chỉ cần một biến này là đủ cho PostgreSQL
      - key: DATABASE_URL
        fromDatabase:
          name: mysql-db # Tên của database service
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

 # --- Dịch vụ Backend Python (Docker) ---
  - name: backend-python
    type: web
    env: docker
    plan: free
    rootDir: ./prediction_service
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
